export interface SystemNode {
  id: string;
  title: string;
  code: string;
  category: string;
  count: string;
  icon: string;
  description: string;
  angle: number; // in degrees for radial distribution
  distance: number; // base radial distance in px
  zDepth: number; // perceived z depth
  route?: string;
}

export const SYSTEM_NODES: SystemNode[] = [
  {
    id: "tasks",
    title: "Tasks",
    code: "#01",
    category: "Workflow",
    count: "3 pending",
    icon: "CheckSquare",
    description: "Priority queue with AI planning",
    angle: 0,
    distance: 320,
    zDepth: 20,
    route: "/deck?view=home",
  },
  {
    id: "habits",
    title: "Habits",
    code: "#02",
    category: "Rhythm",
    count: "7-day streak",
    icon: "Flame",
    description: "Daily rituals & streak matrices",
    angle: 30,
    distance: 420,
    zDepth: -40,
    route: "/deck?view=home",
  },
  {
    id: "focus",
    title: "Focus",
    code: "#03",
    category: "Deep Work",
    count: "25:00 active",
    icon: "Timer",
    description: "Glass Pomodoro with sound cues",
    angle: 60,
    distance: 330,
    zDepth: 50,
    route: "/deck?view=home",
  },
  {
    id: "notes",
    title: "Notes",
    code: "#04",
    category: "Capture",
    count: "12 notes",
    icon: "FileText",
    description: "Scratchpad with AI tidy engine",
    angle: 90,
    distance: 430,
    zDepth: -10,
    route: "/deck?view=home",
  },
  {
    id: "mood",
    title: "Mood",
    code: "#05",
    category: "Wellness",
    count: "Optimal 88%",
    icon: "Smile",
    description: "Living emotion card with aura waveform",
    angle: 120,
    distance: 350,
    zDepth: 30,
    route: "/deck?view=home",
  },
  {
    id: "water",
    title: "Hydration",
    code: "#06",
    category: "Vitality",
    count: "2.1L / 2.5L",
    icon: "Droplets",
    description: "Radial goal ring with smart reminders",
    angle: 150,
    distance: 420,
    zDepth: -50,
    route: "/deck?view=home",
  },
  {
    id: "agenda",
    title: "Agenda",
    code: "#07",
    category: "Schedule",
    count: "4 events",
    icon: "Calendar",
    description: "Temporal calendar & next commitments",
    angle: 180,
    distance: 330,
    zDepth: 40,
    route: "/deck?view=home",
  },
  {
    id: "ai",
    title: "Assistant",
    code: "#08",
    category: "Intelligence",
    count: "Llama 3.3 70B",
    icon: "Sparkles",
    description: "Voice-enabled contextual partner",
    angle: 210,
    distance: 440,
    zDepth: 60,
    route: "/deck?view=assistant",
  },
  {
    id: "software",
    title: "DevHub",
    code: "#09",
    category: "Engineering",
    count: "DSA & Systems",
    icon: "Terminal",
    description: "CS tracks, Big-O matrix & system design",
    angle: 240,
    distance: 340,
    zDepth: -20,
    route: "/deck?view=insights",
  },
  {
    id: "markets",
    title: "Markets",
    code: "#10",
    category: "Financials",
    count: "BTC $94.2k",
    icon: "TrendingUp",
    description: "Real-time crypto & equity tickers",
    angle: 270,
    distance: 420,
    zDepth: 25,
    route: "/deck?view=play",
  },
  {
    id: "studio",
    title: "Studio",
    code: "#11",
    category: "Media",
    count: "yt-dlp active",
    icon: "Youtube",
    description: "Lossless video & audio engine",
    angle: 300,
    distance: 350,
    zDepth: -30,
    route: "/deck?view=studio",
  },
  {
    id: "games",
    title: "Casino",
    code: "#12",
    category: "Entertainment",
    count: "1,000,000 chips",
    icon: "Dices",
    description: "Monochrome roulette, blackjack & poker",
    angle: 330,
    distance: 440,
    zDepth: 10,
    route: "/deck?view=games",
  },
];
